name: release

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile

jobs:
  docker-build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to quay.io container registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            quay.io/monotek/gcloud-mysql:master-${{ github.run_number }}
            quay.io/monotek/gcloud-mysql:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
